name: Go Format

on:
  pull_request_target:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"

      - name: Install
        run: go install mvdan.cc/gofumpt@latest

      - name: Tidy
        run: go mod tidy

      - name: Format
        run: gofumpt -l -w .

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Automated formatting"
