name: Go Format

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.3"

      - name: Install
        run: go install mvdan.cc/gofumpt@latest

      - name: Tidy
        run: go mod tidy

      - name: Format
        run: gofumpt -l -w .

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated formatting"
